version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /pages
    destination: /var/www/html/
  - source: //pages/home.htm
    destination: /var/www/html/pages   
  - source: //pages/forcast.htm
    destination: /var/www/html/pages      
  - source: /app.js
    destination: /var/www/html/    
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

